name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: prepare file
      run: |
        echo 'Starting to create file......'
        touch 1.txt
        echo 'have a good day' + `date +%s` >> 1.txt
        echo 'Create file finished!'
        
    - name: rsync developments
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr --delete
        path: 1.txt
        remote_path: /home/lefttime/Downloads/
        remote_host: ${{ secrets.REMOTE_ALIHOST }}
        remote_user: lefttime
        remote_key: ${{ secrets.ALIYUN_LEFTTIME }}
