name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker Image
    - uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_ALIHOST }}
        key: ${{ secrets.ALIYUN_LEFTTIME }}
        port: 22
        username: lefttime
        script: |
          cd Downloads
          echo "hello, man" >> 1.txt
          echo "have a good day" + `date` >> 1.txt
