name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  private_key: ${{ secrets.ALIYUN_LEFTTIME }}
  remote_host: 
  remote_user: 'lefttime'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: rsync developments
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr --delete
        path: src/
        remote_path: /home/lefttime/Downloads/
        remote_host: ${{ secrets.REMOTE_ALIHOST }}
        remote_user: lefttime
        remote_key: ${{ secrets.ALIYUN_LEFTTIME }}
      run: |
        echo 'Starting to rsync file......'
        echo 'have a good day' + `date +%s`
        rsync -av lefttime-portfolio.tar $REMOTE_USER@$REMOTE_HOST:~/Downloads/.
        echo 'Rsync file finished!'
